export const JpnToEng ={
  ノーマル: {name: 'normal',color: 'DimGray', },
  ほのお: {name: 'fire' ,color: 'Crimson', },
  みず: {name: 'water' ,color: 'DodgerBlue', },
  でんき: {name: 'electric',color: 'GoldenRod', },
  くさ:{name: 'grass' ,color: 'ForestGreen', },
  こおり:{name: 'ice' ,color: 'LightBlue', },
  かくとう:{name: 'fighting',color: 'Maroon', },
  どく: {name: 'poison' ,color: 'RebeccaPurple', },
  じめん: {name: 'ground',color: 'SaddleBrown', },
  ひこう: {name: 'flying' ,color: 'Teal', },
  エスパー:{name: 'psychic',color: 'Orchid', },
  むし:{name: 'bug',color: 'OliveDrab', },
  いわ: {name: 'rock' ,color: 'Olive', },
  ゴースト: {name: 'ghost' ,color: 'Purple', },
  ドラゴン: {name: 'dragon',color: 'MediumPurple', },
  あく: {name: 'dark',color: 'black', },
  はがね: {name: 'steel',color: 'LightSlateGrey', },
  フェアリー: {name: 'fairy',color: 'LightPink', },
}