export const typeNameList ={
  normal: {name: 'ノ',color: 'DimGray', },
  fire: {name:'炎' ,color: 'Crimson', },
  water: {name:'水' ,color: 'DodgerBlue', },
  electric: {name: '雷',color: 'GoldenRod', },
  grass:{name: '草' ,color: 'ForestGreen', },
  ice:{name: '氷' ,color: 'LightBlue', },
  fighting:{name:  '格',color: 'Maroon', },
  poison: {name:'毒' ,color: 'RebeccaPurple', },
  ground: {name: '地',color: 'SaddleBrown', },
  flying: {name:'飛' ,color: 'Teal', },
  psychic:{name:  '超',color: 'Orchid', },
  bug:{name:  '虫',color: 'OliveDrab', },
  rock: {name:'岩' ,color: 'Olive', },
  ghost: {name:'霊' ,color: 'Purple', },
  dragon: {name: '竜',color: 'MediumPurple', },
  dark: {name: '悪',color: 'black', },
  steel: {name: '鋼',color: 'LightSlateGrey', },
  fairy: {name: '妖',color: 'LightPink', },

  ノーマル: {name: 'ノ',color: 'DimGray', },
  ほのお: {name:'炎' ,color: 'Crimson', },
  みず: {name:'水' ,color: 'DodgerBlue', },
  でんき: {name: '雷',color: 'GoldenRod', },
  くさ:{name: '草' ,color: 'ForestGreen', },
  こおり:{name: '氷' ,color: 'LightBlue', },
  かくとう:{name:  '格',color: 'Maroon', },
  どく: {name:'毒' ,color: 'RebeccaPurple', },
  じめん: {name: '地',color: 'SaddleBrown', },
  ひこう: {name:'飛' ,color: 'Teal', },
  エスパー:{name:  '超',color: 'Orchid', },
  むし:{name:  '虫',color: 'OliveDrab', },
  いわ: {name:'岩' ,color: 'Olive', },
  ゴースト: {name:'霊' ,color: 'Purple', },
  ドラゴン: {name: '竜',color: 'MediumPurple', },
  あく: {name: '悪',color: 'black', },
  はがね: {name: '鋼',color: 'LightSlateGrey', },
  フェアリー: {name: '妖',color: 'LightPink', },
}